import "./globals.css";
import MenuComponent from "./_components/Menu";
import styles from "./_styles/layout.module.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  const menuOptions = [
    { id: "0", title: "Recipes" },
    { id: "1", parent: "0", title: "ENTREES" },
    { id: "2", parent: "0", title: "DESSERT" },
    { id: "3", title: "About" },
    { id: "4", title: "Contact" },
  ];
  return (
    <html lang="en">
      <body>
        <header>
          <div className={styles["header-container"]}>
            <MenuComponent menuOptions={menuOptions} />
            <div className={styles["title-icon-wrapper"]}>
              <div className={styles["header-title"]}>
                little leaf cookbook
                <div className={styles["header-subtitle"]}>
                  a catalog of recipes in one place
                </div>
              </div>
              <img className={styles["leaf-icon"]} src="images/leaf.png"></img>
            </div>
            <div></div>
          </div>
        </header>
        {children}
        {/* <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
          }}
        >
          <p>Footer</p>
        </footer> */}
      </body>
    </html>
  );
}
